apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u56e6vlnv-nodejs 
  janus-idp.io/tekton: u56e6vlnv-nodejs
  backstage.io/kubernetes-id: u56e6vlnv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u56e6vlnv-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  